import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, Stack } from '@mui/material';
import { styled } from '@mui/material/styles';
import Grid from '@mui/system/Unstable_Grid/Grid';
import im1 from '../assets/1.jpg'
import Typography from '@mui/material/Typography';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import AppBar from '@mui/material/AppBar';
const inter = Inter({ subsets: ['latin'] })
const backgroundImage = 'https://mui.com/static/themes/onepirate/productCurvyLines.png'

const SIDE_NAV_WIDTH = 280;

const LayoutRoot = styled('div')(({ theme }) => ({
  display: 'flex',
  flex: '1 1 auto',
  maxWidth: '100%',
  marginTop:'4em'
/*   [theme.breakpoints.up('lg')]: {
    paddingLeft: SIDE_NAV_WIDTH
  } */
}));

const LayoutContainer = styled('div')({
  display: 'flex',
  flex: '1 1 auto',
  flexDirection: 'column',
  width: '100%'
});




const darkTheme = createTheme({
    palette: {
      primary: {
        main: '#f5f5f5',
      },
    },
    typography: {
      fontFamily: 'Audiowide',
      fontSize: 20
    },
  });
  

export default function Home() {





return (
    <>
      <Head>
        <title>audice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Audiowide&display=swap" rel="stylesheet"></link>

      </Head>
      <ThemeProvider theme={darkTheme}>
      <Box sx={{ flexGrow: 1 }}>
        <AppBar position="absolute">
          <Toolbar sx={{ height: 100 }}>
          <Box sx={{ margin: 'auto' }}>
        <Typography  variant="h2">audice</Typography>

          </Box>
           
          </Toolbar>
        </AppBar>
      </Box>
    </ThemeProvider>

  <LayoutRoot>
        <LayoutContainer>
      <main >
        <Grid container md={12} sm={12} xl={12} lg={12} direction={'row'} justifyContent={'center'} alignContent={'center'} height={700} style={{ backgroundColor:'black'}} /* sx={{mt:'10'}} */>

        <Grid item md={6} sm={6} xl={6} lg={6} p={15}  /* style={{ backgroundColor:'yellow'}} */>
        <Stack>
        <Typography  align="center" variant="h5" sx={{ mb: 0, mt: { xs: 2, sm: 3 }, color:'white' }}>
          Ofrecemos una interfaz intuitiva y potentes herramientas de mezcla que te permiten crear transiciones suaves, ajustar el tempo, aplicar efectos y mucho más. 
        </Typography>
        <Typography  align="center" variant="h5" sx={{ mb: 0, mt: { xs: 2, sm: 3 }, color:'white' }}>
          Conviértete en el alma de la fiesta y sorprende a tu audiencia con mezclas profesionales y fluidas.
        </Typography>
        <Button color="primary" variant="contained" size="large" component="a" href="/audice" sx={{ mt: 3 }}>
          Try audice
        </Button>
        </Stack>

  </Grid> 
<Grid item p={6} md={6} sm={6} xl={6} lg={6} sx={{  backgroundImage:`url(${backgroundImage})`}}>
  <Image src={im1} width={500} height={600} />

        </Grid>
       
        </Grid>
      </main>

     </LayoutContainer>
      </LayoutRoot>
    </>
  )
}




















































